name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd /home/flask
            git pull origin main
            python -m pip install -r requirements.txt
            python manage.py migrate
            PID=$(systemctl show --value -p MainPID gunicorn.service) && kill -HUP $PID
            echo "Deployment successfull"
